[bumpver]
current_version = "0.0.2"
version_pattern = "MAJOR.MINOR.PATCH[-TAGNUM]"
commit = true
tag = true
push = true

[bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"'
]
"bumpver.toml" = [
    'current_version = "{version}"',
]
